function generate_legacy_wrappers()
%GENERATE_LEGACY_WRAPPERS Generate root-level deprecation wrappers.
%   This script regenerates legacy root-level compatibility wrappers from
%   the single mapping source in scripts/legacy_wrapper_map.m.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
map = legacy_wrapper_map();

helperText = sprintf([ ...
    'function qfiDeprecatedRootApi(legacyName, packageName)\n' ...
    '%%QFIDEPRECATEDROOTAPI Warn about legacy root-level API usage.\n' ...
    'warning(''QFIEntanglementToolbox:DeprecatedRootAPI'', ...\n' ...
    '    [''Legacy root-level function "'', legacyName, ''" is deprecated and will be removed in v2.0.0. '' ...\n' ...
    '     ''Use "'', packageName, ''" instead.'']);\n' ...
    'end\n']);
write_text(fullfile(projectRoot, 'qfiDeprecatedRootApi.m'), helperText);

for i = 1:size(map, 1)
    legacyName = map{i, 1};
    targetName = map{i, 2};
    wrapperText = sprintf([ ...
        'function varargout = %s(varargin)\n' ...
        '%%%s Backward-compatible wrapper for migrated package API.\n' ...
        '%%   Deprecated: use %s instead.\n\n' ...
        'qfiDeprecatedRootApi(''%s'', ''%s'');\n' ...
        'if nargout > 0\n' ...
        '    [varargout{1:nargout}] = %s(varargin{:});\n' ...
        'else\n' ...
        '    %s(varargin{:});\n' ...
        'end\n' ...
        'end\n'], ...
        legacyName, upper(legacyName), targetName, legacyName, targetName, targetName, targetName);
    write_text(fullfile(projectRoot, [legacyName, '.m']), wrapperText);
end

fprintf('Regenerated %d legacy wrappers at project root.\n', size(map, 1));
end

function write_text(path, text)
fid = fopen(path, 'w');
if fid == -1
    error('QFIEntanglementToolbox:WrapperGenerationFailed', ...
        'Unable to open file for writing: %s', path);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fwrite(fid, text, 'char');
end
